version: '3'

services:

  clickhouse:
    restart: always
    image: clickhouse/clickhouse-server:latest
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: qwerty123
    ports:
      - "8123:8123"
      - "9000:9000"
    expose:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/clickhouse/data:/var/lib/clickhouse
    networks:
      - bridge_event_network

  event:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    links:
      - "clickhouse:clickhouse"
    depends_on:
      - clickhouse
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_PASSWORD=qwerty123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_NAME=default
    expose:
      - 8080:8080
    networks:
      - bridge_event_network

networks:
  bridge_event_network:
    driver: bridge
