[Service]
ExposeSwagger=true
Port=8080
ReadTimeout=10
WriteTimeout=120
IdleTimeout=10

[Buffer]
RetriesLeft=3
LoopTimeout=10
Size=60000

[Database]
TableName="test"
DialTimeout=10
MaxOpenConns=5
MaxIdleConns=5
ConnMaxLifetime=3600
Debug=true